#Instead of using TAB for indentation, use two spaces at the place of one TAB

#Controller to control robot arm joints
rover_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [joint_1, joint_2, joint_3, joint_4, joint_5]
  state_tolerances: # Tolerance for each point in the trajectory
    joint_1: 0.01
    joint_2: 0.01 # Relax this tolerance, as joint_2 reported the violation
    joint_3: 0.01
    joint_4: 0.01
    joint_5: 0.01
    
  
  goal_tolerances: # Tolerance for the final point of the trajectory
    joint_1: 0.01
    joint_2: 0.01 # Relax this tolerance as well
    joint_3: 0.01
    joint_4: 0.01
    joint_5: 0.01
    
  # Optional: You can also add a setting for how long the goal must be maintained
  # goal_time_tolerances: # in seconds
  #   joint_1: 0.1
  #   # ... for all joints
  #   state_tolerance: 0.1 # a general state tolerance time
  # -------------------------------------

#Controller to control end effector joints
hand_ee_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [joint_ree]
  # You might also need to add tolerances for the hand_ee_controller if you encounter issues with gripper movements
  state_tolerances:
    joint_ree: 0.01
  goal_tolerances:
    joint_ree: 0.01

#Controller to continuously publish joint states/positions
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50