controller_list:
  - name: fake_Arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
  - name: fake_EE_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_ree
  - name: fake_Rover_group_controller
    type: $(arg fake_execution_type)
    joints:
      - rover_joint
  - name: fake_full_robot_controller
    type: $(arg fake_execution_type)
    joints:
      - rover_joint
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
initial:  # Define initial robot poses per group
  - group: Arm_group
    pose: pose0
  - group: EE_group
    pose: ee_open