controller_list:
  - name: fake_Arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
  - name: fake_EE_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_lee
      - joint_ree
initial:  # Define initial robot poses per group
#  - group: Arm_group
#    pose: home

  []