# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  joint_2:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  joint_3:
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: false
    max_acceleration: 0
  joint_4:
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: false
    max_acceleration: 0
  joint_5:
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: false
    max_acceleration: 0
  joint_ree:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    
  # --- ADDITIONS FOR VIRTUAL JOINT ---
  rover_joint/x:
    has_velocity_limits: true
    max_velocity: 0.5 # Example: Max linear speed of 0.5 m/s in X
    has_acceleration_limits: true
    max_acceleration: 0.5 # Example: Max linear acceleration of 0.5 m/s^2 in X
    has_position_limits: false # Set to true if you want to limit its travel range (e.g., min_position: -10.0, max_position: 10.0)

  rover_joint/y:
    has_velocity_limits: true
    max_velocity: 0.5 # Effectively lock Y translation
    has_acceleration_limits: true
    max_acceleration: 0.5
    has_position_limits: false 

  rover_joint/theta: # This is the Z-axis rotation (yaw)
    has_velocity_limits: true
    max_velocity: 0.001 # Effectively lock Z rotation (yaw)
    has_acceleration_limits: true
    max_acceleration: 0.001
    has_position_limits: true
    min_position: 0.0     # Lock it at 0
    max_position: 0.0     # Lock it at 0 